// File: /backend/services/metadataService.js

const fs = require('fs');
const path = require('path');
const uuid = require('uuid');
const { analyzeFileContent } = require('./aiInsightsService'); // AI insights integration

// In-memory metadata store (replace with database for production)
const metadataStore = {};

// Extract basic metadata for a file
const extractMetadata = async (filePath) => {
    if (!fs.existsSync(filePath)) {
        throw new Error(`File does not exist: ${filePath}`);
    }

    const stats = fs.statSync(filePath);
    return {
        fileId: uuid.v4(),
        fileName: path.basename(filePath),
        filePath: filePath,
        size: stats.size,
        fileType: path.extname(filePath).slice(1),
        createdAt: stats.birthtime,
        updatedAt: stats.mtime,
    };
};

// Save or update metadata for a file
const saveOrUpdateMetadata = async (filePath, customMetadata = {}) => {
    if (!fs.existsSync(filePath)) {
        throw new Error(`File does not exist: ${filePath}`);
    }

    const fileId = path.basename(filePath);

    // Extract basic metadata
    const basicMetadata = await extractMetadata(filePath);

    // Analyze file content for AI-generated tags and insights
    const aiInsights = await analyzeFileContent(fileId, filePath);
    const autoGeneratedMetadata = {
        tags: aiInsights.tags || [],
        summary: aiInsights.summary || '',
    };

    // Combine basic, custom, and AI-generated metadata
    const metadata = {
        ...basicMetadata,
        ...customMetadata,
        ...autoGeneratedMetadata,
    };

    // Store the metadata with versioning
    if (!metadataStore[fileId]) {
        metadataStore[fileId] = [];
    }
    metadataStore[fileId].push({ version: metadataStore[fileId].length + 1, metadata });

    console.log(`Metadata saved for file: ${fileId}`);
    return metadata;
};

// Get metadata for a file (latest version)
const getMetadata = async (filePath) => {
    const fileId = path.basename(filePath);

    if (!metadataStore[fileId] || metadataStore[fileId].length === 0) {
        throw new Error(`Metadata not found for file: ${filePath}`);
    }

    return metadataStore[fileId][metadataStore[fileId].length - 1].metadata;
};

// Get metadata history for a file
const getMetadataHistory = async (filePath) => {
    const fileId = path.basename(filePath);

    if (!metadataStore[fileId]) {
        throw new Error(`Metadata not found for file: ${filePath}`);
    }

    return metadataStore[fileId];
};

// Delete metadata for a file
const deleteMetadata = async (filePath) => {
    const fileId = path.basename(filePath);

    if (!metadataStore[fileId]) {
        throw new Error(`Metadata not found for file: ${filePath}`);
    }

    delete metadataStore[fileId];
    console.log(`Metadata deleted for file: ${fileId}`);
    return { message: 'Metadata deleted successfully.' };
};

// Search metadata based on filters
const searchMetadata = async (filters) => {
    const results = Object.values(metadataStore)
        .map((fileVersions) => fileVersions[fileVersions.length - 1].metadata) // Use the latest version
        .filter((metadata) => {
            return Object.keys(filters).every((key) => {
                if (!metadata[key]) return false;
                if (typeof metadata[key] === 'string') {
                    return metadata[key].toLowerCase().includes(filters[key].toLowerCase());
                }
                if (typeof metadata[key] === 'number') {
                    return metadata[key] === filters[key];
                }
                return true;
            });
        });

    return results;
};

module.exports = {
    extractMetadata,
    saveOrUpdateMetadata,
    getMetadata,
    getMetadataHistory,
    deleteMetadata,
    searchMetadata,
};
